# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: clouders
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: example-function
# "service" is the name of this project. This will also be added to your AWS resource names.
service: example-function

provider:
  name: aws
  runtime: nodejs20.x
  profile: clouders

functions:
  hello:
    handler: handler.hello
